#!/usr/bin/env bash
set -euo pipefail

if [ -n "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS:-}" ]; then
  mapfile -t paths <<< "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}"
else
  paths=("${PWD}")
fi

for path in "${paths[@]}"; do
  dew-encryption container-quick-create "${path}"
done
